//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     163
#define IDB_HEROBACK                    164
#define IDB_HEROFRONT                   165
#define IDB_HEROLEFT                    166
#define IDB_HERORIGHT                   167
#define IDB_BOSSMAP                     169
#define IDB_DOWNLEFT                    170
#define IDB_DOWNRIGHT                   171
#define IDB_UPLEFT                      172
#define IDB_UPRIGHT                     173
#define IDB_BOSS                        174
#define IDB_BOSS_SHADOW                 175
#define IDB_FLOOR                       179
#define IDB_TOPWALL                     180
#define IDB_WALL                        181
#define IDB_DOWNWALL                    182
#define IDB_TOPDOWNWALL                 183
#define IDB_WALLONWALL                  185
#define IDB_WALLDOWNWALL                186
#define IDB_HERO_DOWN                   227
#define IDB_HERO_DOWN2                  228
#define IDB_HERO_DOWN3                  229
#define IDB_HERO_DOWN4                  230
#define IDB_HERO_DOWN5                  231
#define IDB_HERO_DOWN_LEFT              232
#define IDB_HERO_DOWN_LEFT2             233
#define IDB_HERO_DOWN_LEFT3             234
#define IDB_HERO_DOWN_LEFT4             235
#define IDB_HERO_DOWN_LEFT5             236
#define IDB_HERO_DOWN_RIGHT             237
#define IDB_HERO_DOWN_RIGHT2            238
#define IDB_HERO_DOWN_RIGHT3            239
#define IDB_HERO_DOWN_RIGHT4            240
#define IDB_HERO_DOWN_RIGHT5            241
#define IDB_HERO_LEFT                   242
#define IDB_HERO_LEFT2                  243
#define IDB_HERO_LEFT3                  244
#define IDB_HERO_LEFT4                  245
#define IDB_HERO_LEFT5                  246
#define IDB_HERO_RIGHT                  247
#define IDB_HERO_RIGHT2                 248
#define IDB_HERO_RIGHT3                 249
#define IDB_HERO_RIGHT4                 250
#define IDB_HERO_RIGHT5                 251
#define IDB_HERO_UP                     252
#define IDB_HERO_UP2                    253
#define IDB_HERO_UP3                    254
#define IDB_HERO_UP4                    255
#define IDB_HERO_UP5                    256
#define IDB_HERO_UP_LEFT                257
#define IDB_HERO_UP_LEFT2               258
#define IDB_HERO_UP_LEFT3               259
#define IDB_HERO_UP_LEFT4               260
#define IDB_HERO_UP_LEFT5               261
#define IDB_HERO_UP_RIGHT               262
#define IDB_HERO_UP_RIGHT2              263
#define IDB_HERO_UP_RIGHT3              264
#define IDB_HERO_UP_RIGHT4              265
#define IDB_HERO_UP_RIGHT5              266
#define IDB_ARROW_03                    268
#define IDB_ARROW_3                     269
#define IDB_ARROW_6                     270
#define IDB_ARROW_9                     271
#define IDB_ARROW_36                    272
#define IDB_ARROW_69                    273
#define IDB_ARROW_90                    274
#define IDB_BITMAP4                     275
#define IDB_ARROW_NOTHING               275
#define IDB_ARROW_NO                    288
#define IDB_ARROW_0                     289
#define IDB_ARROW_1                     290
#define IDB_ARROW_2                     291
#define IDB_HERO_ROLL_UP1               293
#define IDB_HERO_ROLL_UP2               294
#define IDB_HERO_ROLL_UP3               295
#define IDB_HERO_ROLL_UP4               296
#define IDB_HERO_ROLL_UP5               297
#define IDB_HERO_ROLL_UP6               298
#define IDB_HERO_ROLL_DOWN1             300
#define IDB_HERO_ROLL_DOWN2             301
#define IDB_HERO_ROLL_DOWN3             302
#define IDB_HERO_ROLL_DOWN4             303
#define IDB_HERO_ROLL_DOWN5             304
#define IDB_HERO_ROLL_DOWN6             305
#define IDB_HERO_ROLL_LEFT1             306
#define IDB_HERO_ROLL_LEFT2             307
#define IDB_HERO_ROLL_LEFT3             308
#define IDB_HERO_ROLL_LEFT4             309
#define IDB_HERO_ROLL_LEFT5             310
#define IDB_HERO_ROLL_LEFT6             311
#define IDB_HERO_ROLL_RIGHT1            312
#define IDB_HERO_ROLL_RIGHT2            313
#define IDB_HERO_ROLL_RIGHT3            314
#define IDB_HERO_ROLL_RIGHT4            315
#define IDB_HERO_ROLL_RIGHT5            316
#define IDB_HERO_ROLL_RIGHT6            317
#define IDB_HERO_ROLL_DOWN_LEFT1        318
#define IDB_HERO_ROLL_DOWN_LEFT2        319
#define IDB_HERO_ROLL_DOWN_LEFT3        320
#define IDB_HERO_ROLL_DOWN_LEFT4        321
#define IDB_HERO_ROLL_DOWN_LEFT5        322
#define IDB_HERO_ROLL_DOWN_LEFT6        323
#define IDB_HERO_ROLL_DOWN_RIGHT1       324
#define IDB_HERO_ROLL_DOWN_RIGHT2       325
#define IDB_HERO_ROLL_DOWN_RIGHT3       326
#define IDB_HERO_ROLL_DOWN_RIGHT4       327
#define IDB_HERO_ROLL_DOWN_RIGHT5       328
#define IDB_HERO_ROLL_DOWN_RIGHT6       329
#define IDB_HERO_ROLL_TOP_LEFT1         330
#define IDB_HERO_ROLL_TOP_LEFT2         331
#define IDB_HERO_ROLL_TOP_LEFT3         332
#define IDB_HERO_ROLL_TOP_LEFT4         333
#define IDB_HERO_ROLL_TOP_LEFT5         334
#define IDB_HERO_ROLL_TOP_LEFT6         335
#define IDB_HERO_ROLL_TOP_RIGHT1        336
#define IDB_HERO_ROLL_TOP_RIGHT2        337
#define IDB_HERO_ROLL_TOP_RIGHT3        338
#define IDB_HERO_ROLL_TOP_RIGHT4        339
#define IDB_HERO_ROLL_TOP_RIGHT5        340
#define IDB_BITMAP29                    341
#define IDB_HERO_ROLL_TOP_RIGHT6        341
#define IDB_BOSS_BODY                   347
#define IDB_BITMAP6                     348
#define IDB_BOSS_TOP                    348
#define IDB_BITMAP5                     349
#define IDB_NEGATIVE                    349
#define IDB_BOSS_BODDY_1                351
#define IDB_BOSS_BODDY_2                352
#define IDB_BITMAP9                     353
#define IDB_BOSS_BODDY_3                353
#define IDB_BOSS_BODDY_4                354
#define IDB_BOSS_BODDY_5                355
#define IDB_BITMAP7                     356
#define IDB_FIRE_BALL                   356
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        357
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
